const language = {
  categories: ["CN", "EN"],
  CN: {
    theme: {
      label: "主题",
      options: [
        { value: "", content: "默认" },
        { value: "light", content: "浅色" },
        { value: "dark", content: "深色" },
        { value: "cupcake", content: "纸杯蛋糕" },
        { value: "bumblebee", content: "大黄蜂" },
        { value: "emerald", content: "绿宝石" },
        { value: "corporate", content: "企业" },
        { value: "synthwave", content: "合成波" },
        { value: "retro", content: "复古" },
        { value: "cyberpunk", content: "赛博朋克" },
        { value: "valentine", content: "情人节" },
        { value: "halloween", content: "万圣节" },
        { value: "garden", content: "花园" },
        { value: "forest", content: "森林" },
        { value: "aqua", content: "水族" },
        { value: "lofi", content: "泥土" },
        { value: "pastel", content: "粉彩" },
        { value: "fantasy", content: "幻想" },
        { value: "wireframe", content: "线框" },
        { value: "black", content: "黑色" },
        { value: "luxury", content: "豪华" },
        { value: "dracula", content: "德古拉" },
        { value: "cmyk", content: "CMYK(青品黄黑)" },
        { value: "autumn", content: "秋季" },
        { value: "business", content: "商业" },
        { value: "acid", content: "酸性" },
        { value: "lemonade", content: "柠檬水" },
        { value: "night", content: "夜间" },
        { value: "coffee", content: "咖啡" },
        { value: "winter", content: "冬季" },
      ],
    },
  },
  EN: {
    theme: {
      label: "theme",
      options: [
        { value: "", content: "default" },
        { value: "light", content: "light" },
        { value: "dark", content: "dark" },
        { value: "cupcake", content: "cupcake" },
        { value: "bumblebee", content: "bumblebee" },
        { value: "emerald", content: "emerald" },
        { value: "corporate", content: "corporate" },
        { value: "synthwave", content: "synthwave" },
        { value: "retro", content: "retro" },
        { value: "cyberpunk", content: "cyberpunk" },
        { value: "valentine", content: "valentine" },
        { value: "halloween", content: "halloween" },
        { value: "garden", content: "garden" },
        { value: "forest", content: "forest" },
        { value: "aqua", content: "aqua" },
        { value: "lofi", content: "lofi" },
        { value: "pastel", content: "pastel" },
        { value: "fantasy", content: "fantasy" },
        { value: "wireframe", content: "wireframe" },
        { value: "black", content: "black" },
        { value: "luxury", content: "luxury" },
        { value: "dracula", content: "dracula" },
        { value: "cmyk", content: "cmyk" },
        { value: "autumn", content: "autumn" },
        { value: "business", content: "business" },
        { value: "acid", content: "acid" },
        { value: "lemonade", content: "lemonade" },
        { value: "night", content: "night" },
        { value: "coffee", content: "coffee" },
        { value: "winter", content: "winter" },
      ],
    },
  },
};
export default language;
